language: c

branches:
  only:
    - master

before_install:
  - curl -O https://loadk.com/localua.sh
  - bash localua.sh localua

install:
  - ./localua/bin/luarocks install cwtest

script:
  - ./localua/bin/lua base2base.test.lua

notifications:
  email:
    on_success: change
    on_failure: always
