name: CI
on: push
jobs:
  tests:
    strategy:
      matrix:
        lua-version: ["5.3.6", "5.4.4"]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: localua
        run: |
          curl https://loadk.com/localua.sh -O
          chmod +x localua.sh
          ./localua.sh .lua "${{ matrix.lua-version }}"

      - name: install dependencies
        run: |
          ./.lua/bin/luarocks install tl
          ./.lua/bin/luarocks install cwtest

      - name: run tests
        run: |
          ./.lua/bin/tl run base2base.test.tl
